# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nanofinder.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

# hello
from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import ImageView, PlotItem, PlotWidget, ViewBox, mkPen


class Ui_Scanner(object):
    def setupUi(self, Scanner):
        Scanner.setObjectName("Scanner")
        Scanner.resize(1265, 800)
        Scanner.setMinimumSize(QtCore.QSize(1265, 800))
        self.centralwidget = QtWidgets.QWidget(Scanner)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sampleID = QtWidgets.QLabel(self.centralwidget)
        self.sampleID.setMinimumSize(QtCore.QSize(100, 28))
        self.sampleID.setMaximumSize(QtCore.QSize(200, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.sampleID.setPalette(palette)
        self.sampleID.setAutoFillBackground(True)
        self.sampleID.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.sampleID.setIndent(5)
        self.sampleID.setObjectName("sampleID")
        self.horizontalLayout_7.addWidget(self.sampleID)
        self.sample_name = QtWidgets.QLineEdit(self.centralwidget)
        self.sample_name.setMinimumSize(QtCore.QSize(100, 22))
        self.sample_name.setMaximumSize(QtCore.QSize(200, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.sample_name.setPalette(palette)
        self.sample_name.setObjectName("sample_name")
        self.horizontalLayout_7.addWidget(self.sample_name)
        self.saveDir_button = QtWidgets.QPushButton(self.centralwidget)
        self.saveDir_button.setMaximumSize(QtCore.QSize(200, 50))
        self.saveDir_button.setObjectName("saveDir_button")
        self.horizontalLayout_7.addWidget(self.saveDir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.commentLabel = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.commentLabel.setPalette(palette)
        self.commentLabel.setAutoFillBackground(True)
        self.commentLabel.setObjectName("commentLabel")
        self.commentLabel.setMinimumSize(QtCore.QSize(0, 150))
        self.commentLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.horizontalLayout_12.addWidget(self.commentLabel)
        self.comments = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comments.sizePolicy().hasHeightForWidth())
        self.comments.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comments.setPalette(palette)
        self.comments.setObjectName("comments")
        self.comments.setMinimumSize(QtCore.QSize(200, 150))
        self.comments.setMaximumSize(QtCore.QSize(400, 500))
        self.horizontalLayout_12.addWidget(self.comments)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.liveplot1d = PlotWidget(
            self.centralwidget, viewBox=ViewBox(border=mkPen(color='w', width=2)))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.liveplot1d.sizePolicy().hasHeightForWidth())
        self.liveplot1d.setSizePolicy(sizePolicy)
        self.liveplot1d.setMinimumSize(QtCore.QSize(537, 423))
        self.liveplot1d.setObjectName("liveplot1d")
        self.horizontalLayout_5.addWidget(self.liveplot1d)
        self.liveplot1d.hide()
        img1 = PlotItem()
        self.liveplot = ImageView(self.centralwidget, view=img1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.liveplot.sizePolicy().hasHeightForWidth())
        self.liveplot.setSizePolicy(sizePolicy)
        self.liveplot.setMinimumSize(QtCore.QSize(537, 423))
        self.liveplot.setObjectName("liveplot")
        self.horizontalLayout_5.addWidget(self.liveplot)
        self.ref_plot1d = PlotWidget(
            self.centralwidget, viewBox=ViewBox(border=mkPen(color='w', width=2)))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ref_plot1d.sizePolicy().hasHeightForWidth())
        self.ref_plot1d.setSizePolicy(sizePolicy)
        self.ref_plot1d.setMinimumSize(QtCore.QSize(537, 423))
        self.ref_plot1d.setObjectName("ref_plot1d")
        self.horizontalLayout_5.addWidget(self.ref_plot1d)
        self.ref_plot1d.hide()
        img2 = PlotItem()
        self.ref_plot = ImageView(self.centralwidget, view=img2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ref_plot.sizePolicy().hasHeightForWidth())
        self.ref_plot.setSizePolicy(sizePolicy)
        self.ref_plot.setMinimumSize(QtCore.QSize(536, 423))
        self.ref_plot.setObjectName("ref_plot")
        self.horizontalLayout_5.addWidget(self.ref_plot)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.loadImage_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.loadImage_button.sizePolicy().hasHeightForWidth())
        self.loadImage_button.setSizePolicy(sizePolicy)
        self.loadImage_button.setMinimumSize(QtCore.QSize(100, 28))
        self.loadImage_button.setObjectName("loadImage_button")
        self.horizontalLayout_8.addWidget(self.loadImage_button)
        self.selectImage_Button = QtWidgets.QPushButton(
            'Select Image from Collection', self.centralwidget)
        self.selectImage_Button.setObjectName("selectImage_Button")
        self.horizontalLayout_8.addWidget(self.selectImage_Button)
        self.select_scan_area = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_scan_area.sizePolicy().hasHeightForWidth())
        self.select_scan_area.setSizePolicy(sizePolicy)
        self.select_scan_area.setMinimumSize(QtCore.QSize(107, 28))
        self.select_scan_area.setObjectName("select_scan_area")
        self.horizontalLayout_8.addWidget(self.select_scan_area)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_messagePrompt = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_messagePrompt.setPalette(palette)
        self.lineEdit_messagePrompt.setAutoFillBackground(True)
        self.lineEdit_messagePrompt.setText("")
        self.lineEdit_messagePrompt.setObjectName("lineEdit_messagePrompt")
        self.horizontalLayout.addWidget(self.lineEdit_messagePrompt)
        self.plot_type = QtWidgets.QComboBox(self.centralwidget)
        self.plot_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_type.setObjectName("plot_type")
        self.plot_type.addItem("")
        self.plot_type.addItem("")
        self.plot_type.addItem("")
        self.horizontalLayout.addWidget(self.plot_type)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scan_mode = QtWidgets.QComboBox(self.centralwidget)
        self.scan_mode.setObjectName("scan_mode")
        self.scan_mode.addItem("")
        self.scan_mode.addItem("")
        self.verticalLayout.addWidget(self.scan_mode)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.srate_set = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.srate_set.setMaximumSize(QtCore.QSize(500, 16777215))
        self.srate_set.setAlignment(QtCore.Qt.AlignCenter)
        self.srate_set.setDecimals(4)
        self.srate_set.setMinimum(0.0001)
        self.srate_set.setMaximum(500.0)
        self.srate_set.setSingleStep(0.1)
        self.srate_set.setProperty("value", 50.0)
        self.srate_set.setObjectName("srate_set")
        self.gridLayout.addWidget(self.srate_set, 1, 1, 1, 1)
        self.label_time_per_step = QtWidgets.QLabel(self.centralwidget)
        self.label_time_per_step.setMinimumSize(QtCore.QSize(150, 30))
        self.label_time_per_step.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 255, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 255, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_time_per_step.setPalette(palette)
        self.label_time_per_step.setAutoFillBackground(True)
        self.label_time_per_step.setObjectName("label_time_per_step")
        self.gridLayout.addWidget(self.label_time_per_step, 0, 0, 1, 1)
        self.tperstep_set = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.tperstep_set.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tperstep_set.setAlignment(QtCore.Qt.AlignCenter)
        self.tperstep_set.setDecimals(4)
        self.tperstep_set.setMinimum(0.002)
        self.tperstep_set.setMaximum(10000.0)
        self.tperstep_set.setSingleStep(0.1)
        self.tperstep_set.setObjectName("tperstep_set")
        self.gridLayout.addWidget(self.tperstep_set, 0, 1, 1, 1)
        self.label_scan_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_scan_rate.setMinimumSize(QtCore.QSize(150, 30))
        self.label_scan_rate.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 255, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 255, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_scan_rate.setPalette(palette)
        self.label_scan_rate.setAutoFillBackground(True)
        self.label_scan_rate.setObjectName("label_scan_rate")
        self.gridLayout.addWidget(self.label_scan_rate, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_xaxis = QtWidgets.QLabel(self.centralwidget)
        self.label_xaxis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xaxis.setObjectName("label_xaxis")
        self.horizontalLayout_9.addWidget(self.label_xaxis)
        self.stageX = QtWidgets.QSpinBox(self.centralwidget)
        self.stageX.setAlignment(QtCore.Qt.AlignCenter)
        self.stageX.setObjectName("stageX")
        self.horizontalLayout_9.addWidget(self.stageX)
        self.toolButton_xhome = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_xhome.setObjectName("toolButton_xhome")
        self.horizontalLayout_9.addWidget(self.toolButton_xhome)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_yaxis = QtWidgets.QLabel(self.centralwidget)
        self.label_yaxis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaxis.setObjectName("label_yaxis")
        self.horizontalLayout_11.addWidget(self.label_yaxis)
        self.stageY = QtWidgets.QSpinBox(self.centralwidget)
        self.stageY.setAlignment(QtCore.Qt.AlignCenter)
        self.stageY.setObjectName("stageY")
        self.horizontalLayout_11.addWidget(self.stageY)
        self.toolButton_yhome = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_yhome.setObjectName("toolButton_yhome")
        self.horizontalLayout_11.addWidget(self.toolButton_yhome)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_zaxis = QtWidgets.QLabel(self.centralwidget)
        self.label_zaxis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zaxis.setObjectName("label_zaxis")
        self.horizontalLayout_13.addWidget(self.label_zaxis)
        self.stageZ = QtWidgets.QSpinBox(self.centralwidget)
        self.stageZ.setAlignment(QtCore.Qt.AlignCenter)
        self.stageZ.setObjectName("stageZ")
        self.horizontalLayout_13.addWidget(self.stageZ)
        self.toolButton_zhome = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_zhome.setObjectName("toolButton_zhome")
        self.horizontalLayout_13.addWidget(self.toolButton_zhome)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_stageMove = QtWidgets.QLabel(self.centralwidget)
        self.label_stageMove.setMinimumSize(QtCore.QSize(130, 0))
        self.label_stageMove.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_stageMove.setIndent(-1)
        self.label_stageMove.setObjectName("label_stageMove")
        self.horizontalLayout_10.addWidget(self.label_stageMove)
        self.stageStop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.stageStop_Button.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        self.stageStop_Button.setPalette(palette)
        self.stageStop_Button.setObjectName("stageStop_Button")
        self.horizontalLayout_10.addWidget(self.stageStop_Button)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ysize = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ysize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ysize.setAlignment(QtCore.Qt.AlignCenter)
        self.ysize.setMaximum(1000.0)
        self.ysize.setSingleStep(0.1)
        self.ysize.setProperty("value", 10.0)
        self.ysize.setObjectName("ysize")
        self.gridLayout_4.addWidget(self.ysize, 2, 2, 1, 1)
        self.ystep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ystep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ystep.setAlignment(QtCore.Qt.AlignCenter)
        self.ystep.setReadOnly(False)
        self.ystep.setDecimals(4)
        self.ystep.setMaximum(5.0)
        self.ystep.setSingleStep(0.01)
        self.ystep.setProperty("value", 0.1)
        self.ystep.setObjectName("ystep")
        self.gridLayout_4.addWidget(self.ystep, 2, 3, 1, 1)
        self.label_size = QtWidgets.QLabel(self.centralwidget)
        self.label_size.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_size.setPalette(palette)
        self.label_size.setAutoFillBackground(True)
        self.label_size.setObjectName("label_size")
        self.gridLayout_4.addWidget(self.label_size, 0, 2, 1, 1)
        self.ypoints = QtWidgets.QSpinBox(self.centralwidget)
        self.ypoints.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ypoints.setAlignment(QtCore.Qt.AlignCenter)
        self.ypoints.setMinimum(1)
        self.ypoints.setMaximum(100000)
        self.ypoints.setProperty("value", 100)
        self.ypoints.setObjectName("ypoints")
        self.gridLayout_4.addWidget(self.ypoints, 2, 4, 1, 1)
        self.yscanorder = QtWidgets.QComboBox(self.centralwidget)
        self.yscanorder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.yscanorder.setObjectName("yscanorder")
        self.yscanorder.addItem("")
        self.yscanorder.addItem("")
        self.yscanorder.addItem("")
        self.gridLayout_4.addWidget(self.yscanorder, 2, 5, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zactive = QtWidgets.QCheckBox(self.centralwidget)
        self.zactive.setMaximumSize(QtCore.QSize(50, 16777215))
        self.zactive.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zactive.setText("")
        self.zactive.setObjectName("zactive")
        self.horizontalLayout_4.addWidget(
            self.zactive, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.zaxis = QtWidgets.QLabel(self.centralwidget)
        self.zaxis.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        self.zaxis.setPalette(palette)
        self.zaxis.setObjectName("zaxis")
        self.horizontalLayout_4.addWidget(
            self.zaxis, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.zpos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zpos.setEnabled(False)
        self.zpos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zpos.setAlignment(QtCore.Qt.AlignCenter)
        self.zpos.setDecimals(0)
        self.zpos.setMinimum(-1000.0)
        self.zpos.setMaximum(1000.0)
        self.zpos.setSingleStep(1.0)
        self.zpos.setObjectName("zpos")
        self.gridLayout_4.addWidget(self.zpos, 3, 1, 1, 1)
        self.zstep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zstep.setEnabled(False)
        self.zstep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zstep.setAlignment(QtCore.Qt.AlignCenter)
        self.zstep.setReadOnly(False)
        self.zstep.setDecimals(0)
        self.zstep.setMinimum(1)
        self.zstep.setMaximum(10000)
        self.zstep.setSingleStep(1)
        self.zstep.setProperty("value", 1)
        self.zstep.setObjectName("zstep")
        self.gridLayout_4.addWidget(self.zstep, 3, 3, 1, 1)
        self.zpoints = QtWidgets.QSpinBox(self.centralwidget)
        self.zpoints.setEnabled(False)
        self.zpoints.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zpoints.setAlignment(QtCore.Qt.AlignCenter)
        self.zpoints.setMinimum(1)
        self.zpoints.setMaximum(10000)
        self.zpoints.setProperty("value", 10)
        self.zpoints.setObjectName("zpoints")
        self.gridLayout_4.addWidget(self.zpoints, 3, 4, 1, 1)
        self.zscanorder = QtWidgets.QComboBox(self.centralwidget)
        self.zscanorder.setEnabled(False)
        self.zscanorder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zscanorder.setObjectName("zscanorder")
        self.zscanorder.addItem("")
        self.zscanorder.addItem("")
        self.zscanorder.addItem("")
        self.gridLayout_4.addWidget(self.zscanorder, 3, 5, 1, 1)
        self.xpoints = QtWidgets.QSpinBox(self.centralwidget)
        self.xpoints.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xpoints.setAlignment(QtCore.Qt.AlignCenter)
        self.xpoints.setMinimum(1)
        self.xpoints.setMaximum(100000)
        self.xpoints.setProperty("value", 100)
        self.xpoints.setObjectName("xpoints")
        self.gridLayout_4.addWidget(self.xpoints, 1, 4, 1, 1)
        self.zsize = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zsize.setEnabled(False)
        self.zsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zsize.setAlignment(QtCore.Qt.AlignCenter)
        self.zsize.setDecimals(0)
        self.zsize.setMinimum(1)
        self.zsize.setMaximum(10000)
        self.zsize.setSingleStep(1)
        self.zsize.setProperty("value", 1)
        self.zsize.setObjectName("zsize")
        self.gridLayout_4.addWidget(self.zsize, 3, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.queueStart_Button = QtWidgets.QPushButton(self.centralwidget)
        self.queueStart_Button.setEnabled(False)
        self.queueStart_Button.setMinimumSize(QtCore.QSize(0, 30))
        self.queueStart_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.queueStart_Button.setObjectName("queueStart_Button")
        self.gridLayout_6.addWidget(self.queueStart_Button, 1, 0, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 30))
        self.stop_button.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        self.stop_button.setPalette(palette)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_6.addWidget(self.stop_button, 0, 1, 1, 1)
        self.queueAdd_Button = QtWidgets.QPushButton(self.centralwidget)
        self.queueAdd_Button.setEnabled(False)
        self.queueAdd_Button.setMinimumSize(QtCore.QSize(0, 30))
        self.queueAdd_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.queueAdd_Button.setObjectName("queueAdd_Button")
        self.gridLayout_6.addWidget(self.queueAdd_Button, 1, 1, 1, 1)
        self.queueModify_Button = QtWidgets.QPushButton(self.centralwidget)
        self.queueModify_Button.setEnabled(False)
        self.queueModify_Button.setMinimumSize(QtCore.QSize(0, 30))
        self.queueModify_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.queueModify_Button.setObjectName("queueModify_Button")
        self.gridLayout_6.addWidget(self.queueModify_Button, 1, 2, 1, 1)
        self.scan_type = QtWidgets.QComboBox(self.centralwidget)
        self.scan_type.setMinimumSize(QtCore.QSize(0, 30))
        self.scan_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.scan_type.setObjectName("scan_type")
        self.scan_type.addItem("")
        self.scan_type.addItem("")
        self.gridLayout_6.addWidget(self.scan_type, 0, 2, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 30))
        self.start_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.start_button.setObjectName("start_button")
        self.gridLayout_6.addWidget(self.start_button, 0, 0, 1, 1)
        self.scan_kind = QtWidgets.QComboBox(self.centralwidget)
        self.scan_kind.setMinimumSize(QtCore.QSize(0, 30))
        self.scan_kind.setMaximumSize(QtCore.QSize(150, 16777215))
        self.scan_kind.setObjectName("scan_kind")
        self.scan_kind.addItem("")
        self.scan_kind.addItem("")
        self.scan_kind.addItem("")
        self.scan_kind.addItem("")
        self.gridLayout_6.addWidget(self.scan_kind, 0, 3, 1, 1)
        self.queueScanNext = QtWidgets.QPushButton(self.centralwidget)
        self.queueScanNext.setEnabled(False)
        self.queueScanNext.setMinimumSize(QtCore.QSize(0, 30))
        self.queueScanNext.setMaximumSize(QtCore.QSize(150, 16777215))
        self.queueScanNext.setObjectName("queueScanNext")
        self.gridLayout_6.addWidget(self.queueScanNext, 1, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 4, 0, 1, 6)
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_4.addWidget(self.clear_button, 0, 0, 1, 1)
        self.label_step = QtWidgets.QLabel(self.centralwidget)
        self.label_step.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_step.setPalette(palette)
        self.label_step.setAutoFillBackground(True)
        self.label_step.setObjectName("label_step")
        self.gridLayout_4.addWidget(self.label_step, 0, 3, 1, 1)
        self.label_scan_order = QtWidgets.QLabel(self.centralwidget)
        self.label_scan_order.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_scan_order.setPalette(palette)
        self.label_scan_order.setAutoFillBackground(True)
        self.label_scan_order.setObjectName("label_scan_order")
        self.gridLayout_4.addWidget(self.label_scan_order, 0, 5, 1, 1)
        self.xsize = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xsize.setAlignment(QtCore.Qt.AlignCenter)
        self.xsize.setMaximum(1000.0)
        self.xsize.setSingleStep(0.1)
        self.xsize.setProperty("value", 10.0)
        self.xsize.setObjectName("xsize")
        self.gridLayout_4.addWidget(self.xsize, 1, 2, 1, 1)
        self.label_position = QtWidgets.QLabel(self.centralwidget)
        self.label_position.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_position.setPalette(palette)
        self.label_position.setAutoFillBackground(True)
        self.label_position.setObjectName("label_position")
        self.gridLayout_4.addWidget(self.label_position, 0, 1, 1, 1)
        self.label_points = QtWidgets.QLabel(self.centralwidget)
        self.label_points.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 231, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_points.setPalette(palette)
        self.label_points.setAutoFillBackground(True)
        self.label_points.setObjectName("label_points")
        self.gridLayout_4.addWidget(self.label_points, 0, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xactive = QtWidgets.QCheckBox(self.centralwidget)
        self.xactive.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xactive.setText("")
        self.xactive.setCheckable(True)
        self.xactive.setChecked(True)
        self.xactive.setObjectName("xactive")
        self.horizontalLayout_2.addWidget(
            self.xactive, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.xaxis = QtWidgets.QLabel(self.centralwidget)
        self.xaxis.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        self.xaxis.setPalette(palette)
        self.xaxis.setObjectName("xaxis")
        self.horizontalLayout_2.addWidget(
            self.xaxis, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.xstep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xstep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xstep.setAlignment(QtCore.Qt.AlignCenter)
        self.xstep.setReadOnly(False)
        self.xstep.setDecimals(4)
        self.xstep.setMaximum(5.0)
        self.xstep.setSingleStep(0.01)
        self.xstep.setProperty("value", 0.1)
        self.xstep.setObjectName("xstep")
        self.gridLayout_4.addWidget(self.xstep, 1, 3, 1, 1)
        self.xscanorder = QtWidgets.QComboBox(self.centralwidget)
        self.xscanorder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xscanorder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xscanorder.setObjectName("xscanorder")
        self.xscanorder.addItem("")
        self.xscanorder.addItem("")
        self.gridLayout_4.addWidget(self.xscanorder, 1, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yactive = QtWidgets.QCheckBox(self.centralwidget)
        self.yactive.setMaximumSize(QtCore.QSize(50, 16777215))
        self.yactive.setText("")
        self.yactive.setChecked(True)
        self.yactive.setObjectName("yactive")
        self.horizontalLayout_3.addWidget(
            self.yactive, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.yaxis = QtWidgets.QLabel(self.centralwidget)
        self.yaxis.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        self.yaxis.setPalette(palette)
        self.yaxis.setObjectName("yaxis")
        self.horizontalLayout_3.addWidget(
            self.yaxis, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.xpos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xpos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xpos.setAlignment(QtCore.Qt.AlignCenter)
        self.xpos.setDecimals(0)
        self.xpos.setMinimum(-1000.0)
        self.xpos.setMaximum(1000.0)
        self.xpos.setSingleStep(1.0)
        self.xpos.setObjectName("xpos")
        self.gridLayout_4.addWidget(self.xpos, 1, 1, 1, 1)
        self.ypos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ypos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ypos.setAlignment(QtCore.Qt.AlignCenter)
        self.ypos.setDecimals(0)
        self.ypos.setMinimum(-1000.0)
        self.ypos.setMaximum(1000.0)
        self.ypos.setSingleStep(1.0)
        self.ypos.setObjectName("ypos")
        self.gridLayout_4.addWidget(self.ypos, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        Scanner.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Scanner)
        self.statusbar.setObjectName("statusbar")
        Scanner.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Scanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuScan_Parameters = QtWidgets.QMenu(self.menuSettings)
        self.menuScan_Parameters.setObjectName("menuScan_Parameters")
        Scanner.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(Scanner)
        self.actionExit.setObjectName("actionExit")
        self.actionFocus = QtWidgets.QAction(Scanner)
        self.actionFocus.setObjectName("actionFocus")
        self.actionGalvanometer = QtWidgets.QAction(Scanner)
        self.actionGalvanometer.setObjectName("actionGalvanometer")
        self.actionSteppermotor = QtWidgets.QAction(Scanner)
        self.actionSteppermotor.setObjectName("actionSteppermotor")
        self.actionStart_Camera = QtWidgets.QAction(Scanner)
        self.actionStart_Camera.setObjectName("actionStart_Camera")
        self.actionPlot_Settings = QtWidgets.QAction(Scanner)
        self.actionPlot_Settings.setObjectName("actionPlot_Settings")
        self.actionView_Log = QtWidgets.QAction(Scanner)
        self.actionView_Log.setObjectName("actionView_Log")
        self.actionLoad_Parameters_from_file = QtWidgets.QAction(Scanner)
        self.actionLoad_Parameters_from_file.setObjectName(
            "actionLoad_Parameters_from_file")
        self.actionSave_current_parameters_to_file = QtWidgets.QAction(Scanner)
        self.actionSave_current_parameters_to_file.setObjectName(
            "actionSave_current_parameters_to_file")
        self.actionReset_to_default_parameters = QtWidgets.QAction(Scanner)
        self.actionReset_to_default_parameters.setObjectName(
            "actionReset_to_default_parameters")
        self.actionSet_current_parameters_as_default = QtWidgets.QAction(
            Scanner)
        self.actionSet_current_parameters_as_default.setObjectName(
            "actionSet_current_parameters_as_default")
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionStart_Camera)
        self.menuOptions.addAction(self.actionFocus)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionView_Log)
        self.menuScan_Parameters.addAction(
            self.actionLoad_Parameters_from_file)
        self.menuScan_Parameters.addAction(
            self.actionSave_current_parameters_to_file)
        self.menuScan_Parameters.addAction(
            self.actionReset_to_default_parameters)
        self.menuScan_Parameters.addAction(
            self.actionSet_current_parameters_as_default)
        self.menuSettings.addAction(self.actionGalvanometer)
        self.menuSettings.addAction(self.actionSteppermotor)
        self.menuSettings.addAction(self.menuScan_Parameters.menuAction())
        self.menuSettings.addAction(self.actionPlot_Settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.retranslateUi(Scanner)
        self.plot_type.setCurrentIndex(0)
        self.yscanorder.setCurrentIndex(1)
        self.zscanorder.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Scanner)
        Scanner.setTabOrder(self.clear_button, self.xactive)
        Scanner.setTabOrder(self.xactive, self.yactive)
        Scanner.setTabOrder(self.yactive, self.zactive)
        Scanner.setTabOrder(self.zactive, self.xpos)
        Scanner.setTabOrder(self.xpos, self.ypos)
        Scanner.setTabOrder(self.ypos, self.zpos)
        Scanner.setTabOrder(self.zpos, self.xsize)
        Scanner.setTabOrder(self.xsize, self.ysize)
        Scanner.setTabOrder(self.ysize, self.zsize)
        Scanner.setTabOrder(self.zsize, self.xstep)
        Scanner.setTabOrder(self.xstep, self.ystep)
        Scanner.setTabOrder(self.ystep, self.zstep)
        Scanner.setTabOrder(self.zstep, self.xpoints)
        Scanner.setTabOrder(self.xpoints, self.ypoints)
        Scanner.setTabOrder(self.ypoints, self.zpoints)
        Scanner.setTabOrder(self.zpoints, self.xscanorder)
        Scanner.setTabOrder(self.xscanorder, self.yscanorder)
        Scanner.setTabOrder(self.yscanorder, self.zscanorder)
        Scanner.setTabOrder(self.zscanorder, self.start_button)
        Scanner.setTabOrder(self.start_button, self.stop_button)
        Scanner.setTabOrder(self.stop_button, self.scan_type)
        Scanner.setTabOrder(self.scan_type, self.scan_kind)
        Scanner.setTabOrder(self.scan_kind, self.queueStart_Button)
        Scanner.setTabOrder(self.queueStart_Button, self.queueAdd_Button)
        Scanner.setTabOrder(self.queueAdd_Button, self.queueModify_Button)
        Scanner.setTabOrder(self.queueModify_Button, self.queueScanNext)
        Scanner.setTabOrder(self.queueScanNext, self.scan_mode)
        Scanner.setTabOrder(self.scan_mode, self.tperstep_set)
        Scanner.setTabOrder(self.tperstep_set, self.srate_set)
        Scanner.setTabOrder(self.srate_set, self.stageStop_Button)
        Scanner.setTabOrder(self.stageStop_Button, self.stageX)
        Scanner.setTabOrder(self.stageX, self.stageY)
        Scanner.setTabOrder(self.stageY, self.stageZ)
        Scanner.setTabOrder(self.stageZ, self.toolButton_xhome)
        Scanner.setTabOrder(self.toolButton_xhome, self.toolButton_yhome)
        Scanner.setTabOrder(self.toolButton_yhome, self.toolButton_zhome)
        Scanner.setTabOrder(self.toolButton_zhome, self.sample_name)
        Scanner.setTabOrder(self.sample_name, self.loadImage_button)
        Scanner.setTabOrder(self.loadImage_button, self.selectImage_Button)
        Scanner.setTabOrder(self.selectImage_Button, self.select_scan_area)
        Scanner.setTabOrder(self.select_scan_area, self.plot_type)

    def retranslateUi(self, Scanner):
        _translate = QtCore.QCoreApplication.translate
        Scanner.setWindowTitle(_translate("Scanner", "MainWindow"))
        self.sampleID.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">     Sample ID:</span></p></body></html>"))
        self.saveDir_button.setText(_translate("Scanner", "Save Directory"))
        self.commentLabel.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Add comments to be stored into the saved file.</p></body></html>"))
        self.commentLabel.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Add </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Comments</span></p></body></html>"))
        self.comments.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Anything entered here will be stored into the saved file.</p><p>Please add all necessary information related to the sample and scanning.</p></body></html>"))
        comment = "Sample Details:\nFilter:\nLaser wavelength:\nAttenuater:\nIntensity:\nPolarizer:\nAnalyzer:\nMemo:"
        self.comments.setText(comment)
        font = QtGui.QFont()
        font.setFamily('Serif')
        font.setPointSize(12)
        self.comments.setFont(font)
        self.sample_name.setFont(font)
        self.loadImage_button.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Load a saved Image.</p><p>The starting coordinates are valid only if the sample has not been replaced.</p></body></html>"))
        self.loadImage_button.setText(
            _translate("Scanner", "Load Image from file"))
        self.select_scan_area.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Select the region to be scanned</p></body></html>"))
        self.select_scan_area.setText(
            _translate("Scanner", "Select Scan Area"))
        self.plot_type.setItemText(0, _translate("Scanner", "Raw SHG Data"))
        self.plot_type.setItemText(1, _translate("Scanner", "Reference Data"))
        self.plot_type.setItemText(2, _translate("Scanner", "Processed Data"))
        self.scan_mode.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Select scan mode. Single crystals use transmission mode, and thin-films use reflection mode to scan.</p></body></html>"))
        self.scan_mode.setItemText(0, _translate(
            "Scanner", "Transmission Mode (Single Crystal)"))
        self.scan_mode.setItemText(1, _translate(
            "Scanner", "Reflection Mode (Thin Film)"))
        self.label_time_per_step.setToolTip(
            _translate("Scanner", "Scan time per step"))
        self.label_time_per_step.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Time per step (s)</span></p></body></html>"))
        self.label_scan_rate.setToolTip(_translate(
            "Scanner", "Number of points scanned per second"))
        self.label_scan_rate.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Scan Rate (s</span><span style=\" font-weight:600; vertical-align:super;\">-1</span><span style=\" font-weight:600;\">)</span></p></body></html>"))
        self.label_xaxis.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Shortcut key: Right &amp; Left Arrow</p></body></html>"))
        self.label_xaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">X-Axis </span><span style=\" font-size:10pt; font-weight:600;\">(μm)</span></p></body></html>"))
        self.toolButton_xhome.setText(_translate("Scanner", "..."))
        self.label_yaxis.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Shortcut key: Up &amp; Down Arrow</p></body></html>"))
        self.label_yaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Y-Axis </span><span style=\" font-size:10pt; font-weight:600;\">(μm)</span></p></body></html>"))
        self.toolButton_yhome.setText(_translate("Scanner", "..."))
        self.label_zaxis.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Shortcut key: &quot;Shift+Right&quot; &amp; &quot;Shift+Left&quot; Arrow</p></body></html>"))
        self.label_zaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Z-Axis </span><span style=\" font-size:10pt; font-weight:600;\">(μm)</span></p></body></html>"))
        self.toolButton_zhome.setText(_translate("Scanner", "..."))
        self.label_stageMove.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">STAGE</span></p></body></html>"))
        self.stageStop_Button.setText(_translate("Scanner", "STOP Stage"))
        self.label_size.setToolTip(_translate(
            "Scanner", "Total length of scanned region for each axis"))
        self.label_size.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Size (µm)</span></p></body></html>"))
        self.yscanorder.setItemText(0, _translate("Scanner", "1"))
        self.yscanorder.setItemText(1, _translate("Scanner", "2"))
        self.yscanorder.setItemText(2, _translate("Scanner", "3"))
        self.zactive.setToolTip(_translate("Scanner", "check to scan height"))
        self.zaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z</span></p></body></html>"))
        self.zscanorder.setItemText(0, _translate("Scanner", "1"))
        self.zscanorder.setItemText(1, _translate("Scanner", "2"))
        self.zscanorder.setItemText(2, _translate("Scanner", "3"))
        self.queueStart_Button.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Start the queue measurement</p></body></html>"))
        self.queueStart_Button.setText(_translate("Scanner", "Start Queue"))
        self.stop_button.setToolTip(_translate(
            "Scanner", "Click to abort the scan"))
        self.stop_button.setText(_translate("Scanner", "Stop"))
        self.queueAdd_Button.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Add current measurement parameters to queue</p></body></html>"))
        self.queueAdd_Button.setText(_translate("Scanner", "Add to Queue"))
        self.queueModify_Button.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>View or modify the parameters stored in the queue</p></body></html>"))
        self.queueModify_Button.setText(
            _translate("Scanner", "View/Modify Queue"))
        self.scan_type.setToolTip(_translate("Scanner", "<html><head/><body><p>Select scan style. </p><p>Move laser to scan uses the galvanometer to move the laser while sample is fixed, to create the image.</p><p>Move sample uses the stepper motor to move the sample while laser is fixed.</p><p>Note: height (z) scan can be done only by moving the sample stage.</p></body></html>"))
        self.scan_type.setItemText(0, _translate("Scanner", "Laser Scan"))
        self.scan_type.setItemText(1, _translate("Scanner", "Stage Scan"))
        self.start_button.setToolTip(_translate(
            "Scanner", "Click here to start scanning"))
        self.start_button.setText(_translate("Scanner", "Start"))
        self.scan_kind.setToolTip(_translate("Scanner", "<html><head/><body><p>Select nature of the scan.</p><p>Trace: scans from left(top) to right(bottom)</p><p>Retrace: scans from right(bottom) to left(top)</p><p>Trace and Retrace: Generate two images, one from trace, and another from retrace</p><p>Alternate trace and retrace: Save scan time by scanning one line from left to right, next line from right to left, and so on. </p></body></html>"))
        self.scan_kind.setItemText(0, _translate("Scanner", "Trace"))
        self.scan_kind.setItemText(1, _translate("Scanner", "Retrace"))
        self.scan_kind.setItemText(2, _translate("Scanner", "Trace & Retrace"))
        self.scan_kind.setItemText(3, _translate(
            "Scanner", "Alternate Trace/Retrace"))
        self.queueScanNext.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Skip current measurement, and jump to next measurement in queue</p></body></html>"))
        self.queueScanNext.setText(_translate("Scanner", "Scan Next"))
        self.clear_button.setText(_translate("Scanner", "Clear"))
        self.label_step.setToolTip(_translate(
            "Scanner", "<html><head/><body><p>Distance to move from one point to next. </p><p>This tab cannot be edited here.</p><p>Change number of points to change step size.</p></body></html>"))
        self.label_step.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Step size (µm)</span></p></body></html>"))
        self.label_scan_order.setToolTip(_translate("Scanner", "Set the order of scan direction. 1 is fast scan direction, and so on.\n"
                                                    "Make no two axis have same value."))
        self.label_scan_order.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Scan Order </span></p></body></html>"))
        self.label_position.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\">Start Position</p></body></html>"))
        self.label_points.setToolTip(_translate(
            "Scanner", "Number of points scanned per axis"))
        self.label_points.setText(_translate(
            "Scanner", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Number of Points</span></p></body></html>"))
        self.xactive.setToolTip(_translate("Scanner", "check to scan x-axis"))
        self.xaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X</span></p></body></html>"))
        self.xscanorder.setItemText(0, _translate("Scanner", "1"))
        self.xscanorder.setItemText(1, _translate("Scanner", "2"))
        self.yactive.setToolTip(_translate("Scanner", "check to scan y-axis"))
        self.yaxis.setText(_translate(
            "Scanner", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y</span></p></body></html>"))
        self.menuFile.setTitle(_translate("Scanner", "File"))
        self.menuOptions.setTitle(_translate("Scanner", "Options"))
        self.menuSettings.setTitle(_translate("Scanner", "Settings"))
        self.menuScan_Parameters.setTitle(
            _translate("Scanner", "Scan Parameters"))
        self.actionExit.setText(_translate("Scanner", "Exit"))
        self.actionFocus.setText(_translate("Scanner", "Focus Sample"))
        self.actionGalvanometer.setText(_translate("Scanner", "Galvanometer"))
        self.actionSteppermotor.setText(_translate("Scanner", "Stepper Motor"))
        self.actionStart_Camera.setText(_translate("Scanner", "Start Camera"))
        self.actionLoad_Parameters_from_file.setText(
            _translate("Scanner", "Load Parameters from File"))
        self.actionPlot_Settings.setText(
            _translate("Scanner", "Plot Parameters"))
        self.actionView_Log.setText(_translate("Scanner", "View Log"))
        self.actionSave_current_parameters_to_file.setText(
            _translate("Scanner", "Save current parameters to file"))
        self.actionReset_to_default_parameters.setText(
            _translate("Scanner", "Reset to default parameters"))
        self.actionSet_current_parameters_as_default.setText(
            _translate("Scanner", "Set current parameters as default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scanner = QtWidgets.QMainWindow()
    ui = Ui_Scanner()
    ui.setupUi(Scanner)
    Scanner.show()
    sys.exit(app.exec_())
